import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
import AppBar from '@/components/ui/appBar'
 
export const metadata: Metadata = {
  title: 'Lightning Queue',
  description: 'Generated by create next app',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AppBar />
      <body>{children}</body>
    </html>
  )
}